#!/bin/bash
# A basically sane bash environment.

#########
# PROMPT
#########
#  Don't set PS1 for remote emacs, want full when running inside emacs
if [[ ! -z "$TERM" && ("$TERM" != "dumb" || ! -z "$INSIDE_EMACS") ]]; then
    export PS1='${debian_chroot:+($debian_chroot) }<~~~ \[\e[1;33m\]\u\[\e[0m\]@\[\e[1;32m\]\H\[\e[0m\] ( \t ) \[\e[1;36m\]${PWD}\[\e[0m\] ~~~>\n\[\e[1;36m\]\w\[\e[0m\]${__git_log_date_formats:+$(__git_ps1 "(%s)")} \$ '
    export GIT_PS1_SHOWDIRTYSTATE=true
    export GIT_PS1_SHOWSTASHSTATE=true
    export GIT_PS1_SHOWUNTRACKEDFILES=true
    export GIT_PS1_SHOWUPSTREAM="verbose"
fi

##########
# Color
##########
if [ -z "$LS_COLORS" ];then
    DIRCOLORS_BIN=$(type -P dircolors gdircolors | head -1)
    if [ -n "$DIRCOLORS_BIN" ];then
        test -r ~/.dircolors && eval "$($DIRCOLORS_BIN -b ~/.dircolors)" || eval "$($DIRCOLORS_BIN -b)"
    fi
fi

if [ -n "$LS_COLORS" ];then
    # LS
    alias ll='ls -alF --color=auto'
    alias ls='ls --color=auto'

    # TREE
    HAVE_TREE=$(command -v tree)
    [[ -n "$HAVE_TREE" ]] && alias tree='tree -C'
fi

export GREP_COLOR='3;32'
export GREP_OPTIONS='--color=auto'

##########
# History
##########
HISTFILESIZE=100000
HISTSIZE=10000
# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoreboth:erasedups

# append to the history file, don't overwrite it
shopt -s histappend
# save history file after each command
if [[ ! $PROMPT_COMMAND =~ "history -a" ]]; then
    PROMPT_COMMAND="${PROMPT_COMMAND+$PROMPT_COMMAND ; }history -a"
fi

##########
# Misc
##########
HAVE_VIM=$(command -v vim)
[[ -n "$HAVE_VIM" ]] && export EDITOR=vim
HAVE_LESS=$(command -v less)
if [[ -n "$HAVE_LESS" ]];then
    PAGER="less -FiRwX"
	MANPAGER="less -FiRsX"
else
	PAGER=more
	MANPAGER="$PAGER"
fi
export PAGER MANPAGER

# Ack
ACK_PAGER="$PAGER"
ACK_PAGER_COLOR="$PAGER"

##########
# Autojump
##########
for autojump_dir in "$DOTFILES_DIR/autojump" "$DOTFILES_DIR/autojump/bin";do
    if [[ -f "$autojump_dir/autojump.bash" ]];then
	source "$autojump_dir/autojump.bash"
	PYTHON_BIN=$(type -P python2.7 python2.6 python | head -1)
	alias autojump="/usr/bin/env $PYTHON_BIN $autojump_dir/autojump"
    fi
done
