#!/bin/bash
# A basically sane bash environment.

#########
# PROMPT
#########
export PS1='${debian_chroot:+($debian_chroot) }<~~~ \[\e[1;33m\]\u\[\e[0m\] sur \[\e[1;32m\]\H\[\e[0m\] -( \t )- #\!: \[\e[1;36m\]${PWD}\[\e[0m\] ~~~>\n\[\e[1;36m\]\w\[\e[0m\]${__git_log_date_formats:+$(__git_ps1 "(%s)")} \$ '

##########
# Color
##########
export GREP_COLOR='3;32'
export GREP_OPTIONS='--color=auto'

##########
# History
##########
HISTFILESIZE=10000
HISTSIZE=10000
# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoreboth:erasedups

# append to the history file, don't overwrite it
shopt -s histappend

##########
# Misc
##########
HAVE_VIM=$(command -v vim)
[[ -n "$HAVE_VIM" ]] && export EDITOR=vim
HAVE_LESS=$(command -v less)
if [[ -n "$HAVE_LESS" ]];then
    PAGER="less -FiRwX"
	MANPAGER="less -FiRsX"
else
	PAGER=more
	MANPAGER="$PAGER"
fi
export PAGER MANPAGER

# Ack
ACK_PAGER="$PAGER"
ACK_PAGER_COLOR="$PAGER"

##########
# Autojump
##########
if [[ -f "$DOTFILES_DIR/autojump/autojump.bash" ]];then
    source "$DOTFILES_DIR/autojump/autojump.bash"
    PYTHON_BIN=$(type -P python2.7 python2.6 python | head -1)
    eval "autojump() { /usr/bin/env $PYTHON_BIN $DOTFILES_DIR/autojump/autojump; }"
fi
