#!/bin/bash
# A basically sane bash environment.

##########
# Color
##########
if [ -z "$LS_COLORS" ];then
    DIRCOLORS_BIN=$(type -P dircolors gdircolors | head -1)
    if [ -n "$DIRCOLORS_BIN" ];then
        test -r ~/.dircolors && eval "$($DIRCOLORS_BIN -b ~/.dircolors)" || eval "$($DIRCOLORS_BIN -b)"
    fi
fi

if [ -n "$LS_COLORS" ];then
    # LS
    alias ll='ls -alF --color=auto'
    alias ls='ls --color=auto'

    # TREE
    HAVE_TREE=$(type -P tree)
    [[ -n "$HAVE_TREE" ]] && alias tree='tree -C'
fi

export GREP_COLOR='3;32'
export GREP_OPTIONS='--color=auto'

##########
# History
##########
HISTFILESIZE=100000
HISTSIZE=10000
# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoreboth:erasedups

# append to the history file, don't overwrite it
shopt -s histappend
# save history file after each command
if [[ ! $PROMPT_COMMAND =~ "history -a" ]]; then
    PROMPT_COMMAND="${PROMPT_COMMAND+$PROMPT_COMMAND ; }history -a"
fi

##########
# Misc
##########
HAVE_VIM=$(type -P vim)
[[ -n "$HAVE_VIM" ]] && export EDITOR=vim
HAVE_LESS=$(type -P less)
if [[ -n "$HAVE_LESS" ]];then
    export LESS='-FiRX'
    PAGER='less -FiRX'
    MANPAGER='less -FiRsX'
else
	PAGER=more
	MANPAGER="$PAGER"
fi
export PAGER MANPAGER

# lesspipe.sh & code2color
LESSPIPESH_BIN=$(type -P lesspipe.sh)
if [[ -n $(type -P code2color) && -n "$LESSPIPESH_BIN" ]];then
    export LESSOPEN="|$LESSPIPESH_BIN %s"
fi

# Ack
ACK_PAGER="$PAGER"
ACK_PAGER_COLOR="$PAGER"

##########
# Autojump
##########
for autojump_dir in "$DOTFILES_DIR/autojump" "$DOTFILES_DIR/autojump/bin";do
    if [[ -f "$autojump_dir/autojump.bash" ]];then
	source "$autojump_dir/autojump.bash"
	export AUTOJUMP_PYTHON_BIN=$(type -P python2.7 python2.6 python | head -1)
	export AUTOJUMP_BIN="$autojump_dir/autojump"
    fi
done
unset autojump_dir

##############
# todo.txt-cli
##############
if [[ -d "$HOME/.todo" && -f "$HOME/.todo.cfg" ]];then
     export TODOTXT_CFG_FILE="$HOME/.todo.cfg"
     alias t='todo.sh'
     complete -F _todo t
fi

#########
# PROMPT
#########
#  Don't set PS1 for remote emacs, want full when running inside emacs
if [[ ! -z "$TERM" && ("$TERM" != "dumb" || ! -z "$INSIDE_EMACS") ]]; then
    source $DOTFILES_DIR/bash/prompt
fi
